export const catalogCrData = [
    {
        id: 1,
        img: "https://global-mt.ru/upload/iblock/b43/1isi80490zvej6oyamc3gsylgdftzeyw/10k11.png",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "999 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213596134",
        naliche: "В наличии",
    },
    {
        id: 2,
        img: "https://global-mt.ru/upload/iblock/0cc/z5ewycempc7q5y0ndz0ydmmyn6n6ljwm.jpg",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "112 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "21313156634",
        naliche: "В наличии",
    },
    {
        id: 3,
        img: "https://global-mt.ru/upload/iblock/208/2pphr5vxq0jjz4gk7ofhwe0hwwret6p4.jpg",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "240 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213139864",
        naliche: "В наличии",
    },
    {
        id: 4,
        img: "https://global-mt.ru/upload/iblock/99c/f4culrnhumf342o2d1hcx4sc77hn2a6z.jpg",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "320 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "211353134",
        naliche: "В наличии",
    },
    {
        id: 5,
        img: "https://global-mt.ru/upload/iblock/858/tl01x1mu2hqcw7j3rmhmwqe8rjkhqi0r.jpg",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "1 390 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "2131356434",
        naliche: "В наличии",
    },
    {
        id: 5,
        img: "https://global-mt.ru/upload/iblock/75c/cfxiu5io9zlpeqxubaub4fzue6at21e8.jpg",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "30 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "2131345434",
        naliche: "В наличии",
    },
    {
        id: 6,
        img: "https://global-mt.ru/upload/iblock/2b9/fxww4q10pv3293p89z5ih8airw4swkix.jpg",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "309 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "983526",
        naliche: "В наличии",
    },
    {
        id: 7,
        img: "https://global-mt.ru/upload/iblock/b43/1isi80490zvej6oyamc3gsylgdftzeyw/10k11.png",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "180 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213234",
        naliche: "В наличии",
    },
    {
        id: 8,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
    },
]